# -*- coding: utf-8 -*-
"""Airbnb_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xmdw0k9HZUsMJrvIqizv2GiTtMVnpiLg
"""

#!pip install streamlit snowflake-connector-python pandas plotly

# Commented out IPython magic to ensure Python compatibility.
# %%writefile airbnb_dashboard.py

#!pip install streamlit snowflake-connector-python pandas plotly
#!npm install -g localtunnel

#streamlit run airbnb_dashboard.py

# -*- coding: utf-8 -*-
"""
Airbnb KPI Dashboard - Streamlit
Διαβάζει απ' ευθείας τα KPI Views από Snowflake και εμφανίζει
διαδραστικό dashboard για KOSTAS ACROPOLIS STUDIO 1 & 2.

Εκτέλεση:
    !pip install streamlit snowflake-connector-python pandas plotly
    !streamlit run airbnb_dashboard.py
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import snowflake.connector

# ─────────────────────────────────────────────
# SNOWFLAKE CREDENTIALS  ← βάλε τα δικά σου
# ─────────────────────────────────────────────
SNOWFLAKE_ACCOUNT   = "VFHKJRE-GP30607"          # π.χ. "abc12345.eu-west-1"
SNOWFLAKE_USER      = "KOSTAS"
SNOWFLAKE_PASSWORD  = "Mpotsi!1kostas"
SNOWFLAKE_DB        = "AIRBNB_DB"
SNOWFLAKE_SCHEMA    = "RAW"
SNOWFLAKE_WH        = "AIRBNB_WH"

# ─────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────
st.set_page_config(
    page_title="Airbnb KPI Dashboard",
    page_icon="🏠",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────
# CSS – minimal custom styling
# ─────────────────────────────────────────────
st.markdown("""
<style>
    .metric-card {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 1rem 1.2rem;
        border-radius: 12px;
        color: white;
        text-align: center;
        margin-bottom: 0.5rem;
    }
    .metric-card h3 { margin: 0; font-size: 0.8rem; opacity: 0.85; }
    .metric-card h2 { margin: 0.2rem 0 0 0; font-size: 1.6rem; font-weight: 700; }

    .section-header {
        border-left: 4px solid #FF5A5F;
        padding-left: 0.6rem;
        margin-bottom: 0.8rem;
        color: #FF5A5F;
    }
    div[data-testid="metric-container"] > label { font-size: 0.78rem !important; }
</style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────
# SNOWFLAKE CONNECTION  (cached)
# ─────────────────────────────────────────────
@st.cache_resource
def get_connection():
    return snowflake.connector.connect(
        account   = SNOWFLAKE_ACCOUNT,
        user      = SNOWFLAKE_USER,
        password  = SNOWFLAKE_PASSWORD,
        database  = SNOWFLAKE_DB,
        schema    = SNOWFLAKE_SCHEMA,
        warehouse = SNOWFLAKE_WH,
    )

@st.cache_data(ttl=300)   # refresh κάθε 5 λεπτά
def load_kpi(view: str) -> pd.DataFrame:
    conn = get_connection()
    df = pd.read_sql(f"SELECT * FROM AIRBNB_DB.RAW.{view}", conn)
    df.columns = [c.upper() for c in df.columns]
    return df

@st.cache_data(ttl=300)
def load_lead(view: str) -> pd.DataFrame:
    conn = get_connection()
    df = pd.read_sql(f"SELECT * FROM AIRBNB_DB.RAW.{view}", conn)
    df.columns = [c.upper() for c in df.columns]
    return df

# ─────────────────────────────────────────────
# MONTH ORDER helper
# ─────────────────────────────────────────────
MONTH_ORDER = ["Jan","Feb","Mar","Apr","May","Jun",
               "Jul","Aug","Sep","Oct","Nov","Dec"]

def sort_kpi(df: pd.DataFrame) -> pd.DataFrame:
    if "MONTH" in df.columns:
        df["_mo"] = pd.Categorical(df["MONTH"], categories=MONTH_ORDER, ordered=True)
        df = df.sort_values("_mo").drop(columns="_mo")
    return df.reset_index(drop=True)

# ─────────────────────────────────────────────
# SIDEBAR
# ─────────────────────────────────────────────
with st.sidebar:
    st.image("https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_Bélo.svg", width=120)
    st.markdown("## ⚙️ Ρυθμίσεις")

    studio_sel = st.multiselect(
        "Επιλογή Studio",
        options=["Studio 1 – Acropolis", "Studio 2 – Acropolis"],
        default=["Studio 1 – Acropolis", "Studio 2 – Acropolis"],
    )

    st.markdown("---")
    st.markdown("**KPI Views**")
    st.markdown("✅ KOSTAS_1_KPI")
    st.markdown("✅ KOSTAS_2_KPI")
    st.markdown("✅ KOSTAS_1_KPI_LEAD_TIME")
    st.markdown("✅ KOSTAS_2_KPI_LEAD_TIME")
    st.markdown("---")

    if st.button("🔄 Ανανέωση δεδομένων"):
        st.cache_data.clear()
        st.rerun()

    st.caption("Δεδομένα από Snowflake · Refresh κάθε 5′")

# ─────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────
with st.spinner("Φόρτωση δεδομένων από Snowflake…"):
    try:
        df1     = sort_kpi(load_kpi("KOSTAS_1_KPI"))
        df2     = sort_kpi(load_kpi("KOSTAS_2_KPI"))
        df1_lt  = load_lead("KOSTAS_1_KPI_LEAD_TIME")
        df2_lt  = load_lead("KOSTAS_2_KPI_LEAD_TIME")
        data_ok = True
    except Exception as e:
        st.error(f"❌ Σφάλμα σύνδεσης Snowflake: {e}")
        st.info("Βεβαιώσου ότι έχεις ορίσει σωστά τα credentials στην αρχή του αρχείου.")
        data_ok = False

if not data_ok:
    st.stop()

# Filter by studio selection
show1 = "Studio 1 – Acropolis" in studio_sel
show2 = "Studio 2 – Acropolis" in studio_sel

# ─────────────────────────────────────────────
# HEADER
# ─────────────────────────────────────────────
st.markdown("# 🏠 Airbnb KPI Dashboard")
st.markdown("### Kostas Acropolis Studios · Athens")
st.markdown("---")

# ─────────────────────────────────────────────
# TOP-LEVEL KPI CARDS  (combined or per studio)
# ─────────────────────────────────────────────
def kpi_totals(df):
    return {
        "revenue":      df["PAYMENT"].sum() if "PAYMENT" in df.columns else 0,
        "revenue_net":  df["PAYMENT_NET"].sum() if "PAYMENT_NET" in df.columns else 0,
        "booked_days":  df["TOTAL_BOOKED_DAYS"].sum() if "TOTAL_BOOKED_DAYS" in df.columns else 0,
        "avg_occ":      df["OCCUPANCY_RATE"].mean() if "OCCUPANCY_RATE" in df.columns else 0,
        "avg_adr":      df["AVERAGE_DAILY_RATE"].mean() if "AVERAGE_DAILY_RATE" in df.columns else 0,
        "avg_revpar":   df["REVENUE_PER_AVAILABLE_ROOM"].mean() if "REVENUE_PER_AVAILABLE_ROOM" in df.columns else 0,
    }

frames_active = []
if show1: frames_active.append(df1)
if show2: frames_active.append(df2)

if frames_active:
    combined = pd.concat(frames_active).groupby("MONTH", observed=True).sum(numeric_only=True).reset_index()
    t = kpi_totals(combined if len(frames_active) == 2 else frames_active[0])

    c1, c2, c3, c4, c5, c6 = st.columns(6)
    c1.metric("💰 Συνολικά Έσοδα", f"€{t['revenue']:,.0f}")
    c2.metric("💵 Καθαρά Έσοδα", f"€{t['revenue_net']:,.0f}")
    c3.metric("🛏️ Booked Days", f"{t['booked_days']:.0f}")
    c4.metric("📊 Μ.Ο. Occupancy", f"{t['avg_occ']:.1f}%")
    c5.metric("💲 Μ.Ο. ADR", f"€{t['avg_adr']:.0f}")
    c6.metric("📈 Μ.Ο. RevPAR", f"€{t['avg_revpar']:.0f}")

st.markdown("---")

# ─────────────────────────────────────────────
# TABS
# ─────────────────────────────────────────────
tab1, tab2, tab3, tab4 = st.tabs([
    "📊 Έσοδα & Occupancy",
    "💲 Τιμολόγηση",
    "⏱️ Lead Time",
    "📋 Αναλυτικά Δεδομένα",
])

# ════════════════════════════════════════════
# TAB 1 – REVENUE & OCCUPANCY
# ════════════════════════════════════════════
with tab1:
    st.markdown('<h3 class="section-header">Μηνιαία Έσοδα (Payment)</h3>', unsafe_allow_html=True)

    # Revenue bar chart
    rev_data = []
    if show1 and not df1.empty:
        for _, r in df1.iterrows():
            rev_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 1", "Έσοδα (€)": r.get("PAYMENT", 0)})
    if show2 and not df2.empty:
        for _, r in df2.iterrows():
            rev_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 2", "Έσοδα (€)": r.get("PAYMENT", 0)})

    if rev_data:
        df_rev = pd.DataFrame(rev_data)
        df_rev["Μήνας"] = pd.Categorical(df_rev["Μήνας"], categories=MONTH_ORDER, ordered=True)
        df_rev = df_rev.sort_values("Μήνας")
        fig_rev = px.bar(
            df_rev, x="Μήνας", y="Έσοδα (€)", color="Studio", barmode="group",
            color_discrete_map={"Studio 1": "#FF5A5F", "Studio 2": "#00A699"},
            title="Μηνιαία Έσοδα ανά Studio",
            text_auto=".0f",
        )
        fig_rev.update_traces(textposition="outside")
        fig_rev.update_layout(height=400, plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
        st.plotly_chart(fig_rev, use_container_width=True)

    # Occupancy + Booked Days
    col_a, col_b = st.columns(2)

    with col_a:
        st.markdown('<h3 class="section-header">Occupancy Rate %</h3>', unsafe_allow_html=True)
        occ_data = []
        if show1 and "OCCUPANCY_RATE" in df1.columns:
            for _, r in df1.iterrows():
                occ_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 1", "Occupancy %": r["OCCUPANCY_RATE"]})
        if show2 and "OCCUPANCY_RATE" in df2.columns:
            for _, r in df2.iterrows():
                occ_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 2", "Occupancy %": r["OCCUPANCY_RATE"]})
        if occ_data:
            df_occ = pd.DataFrame(occ_data)
            df_occ["Μήνας"] = pd.Categorical(df_occ["Μήνας"], categories=MONTH_ORDER, ordered=True)
            df_occ = df_occ.sort_values("Μήνας")
            fig_occ = px.line(
                df_occ, x="Μήνας", y="Occupancy %", color="Studio", markers=True,
                color_discrete_map={"Studio 1": "#FF5A5F", "Studio 2": "#00A699"},
            )
            fig_occ.add_hline(y=80, line_dash="dash", line_color="orange",
                              annotation_text="Target 80%", annotation_position="bottom right")
            fig_occ.update_layout(height=320, plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig_occ, use_container_width=True)

    with col_b:
        st.markdown('<h3 class="section-header">Ημέρες Κράτησης vs Ημέρες Μήνα</h3>', unsafe_allow_html=True)
        days_data = []
        if show1 and "TOTAL_BOOKED_DAYS" in df1.columns:
            for _, r in df1.iterrows():
                days_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 1",
                                  "Booked Days": r["TOTAL_BOOKED_DAYS"], "Days in Month": r.get("DAYS", 30)})
        if show2 and "TOTAL_BOOKED_DAYS" in df2.columns:
            for _, r in df2.iterrows():
                days_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 2",
                                  "Booked Days": r["TOTAL_BOOKED_DAYS"], "Days in Month": r.get("DAYS", 30)})
        if days_data:
            df_days = pd.DataFrame(days_data)
            df_days["Μήνας"] = pd.Categorical(df_days["Μήνας"], categories=MONTH_ORDER, ordered=True)
            df_days = df_days.sort_values("Μήνας")
            fig_days = px.bar(
                df_days, x="Μήνας", y=["Booked Days","Days in Month"],
                barmode="overlay", opacity=0.7,
                color_discrete_map={"Booked Days": "#FF5A5F", "Days in Month": "#e0e0e0"},
                facet_col="Studio" if (show1 and show2) else None,
            )
            fig_days.update_layout(height=320, plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig_days, use_container_width=True)

    # Net vs Gross Revenue comparison
    st.markdown('<h3 class="section-header">Gross vs Net Έσοδα</h3>', unsafe_allow_html=True)
    gn_data = []
    if show1 and "PAYMENT_NET" in df1.columns:
        for _, r in df1.iterrows():
            gn_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 1",
                            "Gross": r.get("PAYMENT", 0), "Net": r.get("PAYMENT_NET", 0)})
    if show2 and "PAYMENT_NET" in df2.columns:
        for _, r in df2.iterrows():
            gn_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 2",
                            "Gross": r.get("PAYMENT", 0), "Net": r.get("PAYMENT_NET", 0)})
    if gn_data:
        df_gn = pd.DataFrame(gn_data)
        df_gn["Μήνας"] = pd.Categorical(df_gn["Μήνας"], categories=MONTH_ORDER, ordered=True)
        df_gn = df_gn.sort_values("Μήνας")
        fig_gn = px.bar(
            df_gn.melt(id_vars=["Μήνας","Studio"], value_vars=["Gross","Net"],
                       var_name="Τύπος", value_name="€"),
            x="Μήνας", y="€", color="Τύπος", barmode="group",
            facet_col="Studio" if (show1 and show2) else None,
            color_discrete_map={"Gross": "#FF5A5F", "Net": "#00A699"},
            title="Gross vs Net Πληρωμή ανά Μήνα",
        )
        fig_gn.update_layout(height=360, plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
        st.plotly_chart(fig_gn, use_container_width=True)

# ════════════════════════════════════════════
# TAB 2 – PRICING KPIs
# ════════════════════════════════════════════
with tab2:
    col_p1, col_p2 = st.columns(2)

    with col_p1:
        st.markdown('<h3 class="section-header">Average Daily Rate (ADR)</h3>', unsafe_allow_html=True)
        adr_data = []
        if show1 and "AVERAGE_DAILY_RATE" in df1.columns:
            for _, r in df1.iterrows():
                adr_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 1", "ADR (€)": r["AVERAGE_DAILY_RATE"]})
        if show2 and "AVERAGE_DAILY_RATE" in df2.columns:
            for _, r in df2.iterrows():
                adr_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 2", "ADR (€)": r["AVERAGE_DAILY_RATE"]})
        if adr_data:
            df_adr = pd.DataFrame(adr_data)
            df_adr["Μήνας"] = pd.Categorical(df_adr["Μήνας"], categories=MONTH_ORDER, ordered=True)
            df_adr = df_adr.sort_values("Μήνας")
            fig_adr = px.line(
                df_adr, x="Μήνας", y="ADR (€)", color="Studio", markers=True,
                color_discrete_map={"Studio 1": "#FF5A5F", "Studio 2": "#00A699"},
            )
            fig_adr.update_layout(height=320, plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig_adr, use_container_width=True)

    with col_p2:
        st.markdown('<h3 class="section-header">RevPAR (Revenue per Available Room)</h3>', unsafe_allow_html=True)
        revpar_data = []
        if show1 and "REVENUE_PER_AVAILABLE_ROOM" in df1.columns:
            for _, r in df1.iterrows():
                revpar_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 1", "RevPAR (€)": r["REVENUE_PER_AVAILABLE_ROOM"]})
        if show2 and "REVENUE_PER_AVAILABLE_ROOM" in df2.columns:
            for _, r in df2.iterrows():
                revpar_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 2", "RevPAR (€)": r["REVENUE_PER_AVAILABLE_ROOM"]})
        if revpar_data:
            df_rp = pd.DataFrame(revpar_data)
            df_rp["Μήνας"] = pd.Categorical(df_rp["Μήνας"], categories=MONTH_ORDER, ordered=True)
            df_rp = df_rp.sort_values("Μήνας")
            fig_rp = px.bar(
                df_rp, x="Μήνας", y="RevPAR (€)", color="Studio", barmode="group",
                color_discrete_map={"Studio 1": "#FF5A5F", "Studio 2": "#00A699"},
            )
            fig_rp.update_layout(height=320, plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig_rp, use_container_width=True)

    # Nightly Rate trend
    st.markdown('<h3 class="section-header">Μέση Νυχτερινή Τιμή (Nightly Rate)</h3>', unsafe_allow_html=True)
    nr_data = []
    if show1 and "NIGHTLY_RATE" in df1.columns:
        for _, r in df1.iterrows():
            nr_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 1", "Nightly Rate (€)": r["NIGHTLY_RATE"]})
    if show2 and "NIGHTLY_RATE" in df2.columns:
        for _, r in df2.iterrows():
            nr_data.append({"Μήνας": r["MONTH"], "Studio": "Studio 2", "Nightly Rate (€)": r["NIGHTLY_RATE"]})
    if nr_data:
        df_nr = pd.DataFrame(nr_data)
        df_nr["Μήνας"] = pd.Categorical(df_nr["Μήνας"], categories=MONTH_ORDER, ordered=True)
        df_nr = df_nr.sort_values("Μήνας")
        fig_nr = px.area(
            df_nr, x="Μήνας", y="Nightly Rate (€)", color="Studio",
            color_discrete_map={"Studio 1": "#FF5A5F", "Studio 2": "#00A699"},
            title="Εξέλιξη Νυχτερινής Τιμής ανά Μήνα",
        )
        fig_nr.update_layout(height=350, plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
        st.plotly_chart(fig_nr, use_container_width=True)

    # Summary comparison table
    st.markdown('<h3 class="section-header">Συγκριτικός Πίνακας KPIs</h3>', unsafe_allow_html=True)
    summary_rows = []
    kpi_cols = ["MONTH", "PAYMENT", "PAYMENT_NET", "TOTAL_BOOKED_DAYS",
                "OCCUPANCY_RATE", "AVERAGE_DAILY_RATE", "REVENUE_PER_AVAILABLE_ROOM", "NIGHTLY_RATE"]
    if show1:
        tmp = df1[[c for c in kpi_cols if c in df1.columns]].copy()
        tmp.insert(0, "Studio", "Studio 1")
        summary_rows.append(tmp)
    if show2:
        tmp = df2[[c for c in kpi_cols if c in df2.columns]].copy()
        tmp.insert(0, "Studio", "Studio 2")
        summary_rows.append(tmp)
    if summary_rows:
        df_summ = pd.concat(summary_rows)
        df_summ = df_summ.rename(columns={
            "MONTH": "Μήνας", "PAYMENT": "Gross €", "PAYMENT_NET": "Net €",
            "TOTAL_BOOKED_DAYS": "Booked Days", "OCCUPANCY_RATE": "Occupancy %",
            "AVERAGE_DAILY_RATE": "ADR €", "REVENUE_PER_AVAILABLE_ROOM": "RevPAR €",
            "NIGHTLY_RATE": "Nightly Rate €",
        })
        # Format numbers
        float_cols = ["Gross €", "Net €", "ADR €", "RevPAR €", "Nightly Rate €", "Occupancy %"]
        for c in float_cols:
            if c in df_summ.columns:
                df_summ[c] = df_summ[c].map(lambda x: f"{x:,.1f}" if pd.notna(x) else "")
        st.dataframe(df_summ, use_container_width=True, hide_index=True)

# ════════════════════════════════════════════
# TAB 3 – LEAD TIME
# ════════════════════════════════════════════
with tab3:
    st.markdown('<h3 class="section-header">Lead Time – Πόσο νωρίς κάνουν κράτηση</h3>', unsafe_allow_html=True)
    st.caption("Lead Time = ημέρες μεταξύ booking date και check-in date")

    lt_frames = {}
    if show1 and not df1_lt.empty: lt_frames["Studio 1"] = df1_lt
    if show2 and not df2_lt.empty: lt_frames["Studio 2"] = df2_lt

    if lt_frames:
        # Global avg metric cards
        cols_lt = st.columns(len(lt_frames))
        for idx, (studio, df_lt) in enumerate(lt_frames.items()):
            if "GLOBAL_AVG_LEAD_TIME" in df_lt.columns:
                avg = df_lt["GLOBAL_AVG_LEAD_TIME"].iloc[0]
                cols_lt[idx].metric(f"🕐 Γενικός Μ.Ο. Lead Time – {studio}", f"{avg:.1f} ημέρες")

        st.markdown("")

        # Distribution histogram
        hist_data = []
        for studio, df_lt in lt_frames.items():
            if "LEAD_TIME_DAYS" in df_lt.columns:
                for v in df_lt["LEAD_TIME_DAYS"].dropna():
                    hist_data.append({"Studio": studio, "Lead Time (ημέρες)": v})
        if hist_data:
            fig_hist = px.histogram(
                pd.DataFrame(hist_data),
                x="Lead Time (ημέρες)", color="Studio", barmode="overlay",
                nbins=30, opacity=0.75,
                color_discrete_map={"Studio 1": "#FF5A5F", "Studio 2": "#00A699"},
                title="Κατανομή Lead Time",
            )
            fig_hist.update_layout(height=360, plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig_hist, use_container_width=True)

        # Monthly avg lead time per studio
        col_lt1, col_lt2 = st.columns(2)
        chart_cols = [col_lt1, col_lt2]
        for idx, (studio, df_lt) in enumerate(lt_frames.items()):
            with chart_cols[idx]:
                if "MONTHLY_AVG_LEAD_TIME" in df_lt.columns and "CHECK_IN_DATE_CONVERTED" in df_lt.columns:
                    df_lt2 = df_lt.copy()
                    df_lt2["CHECK_IN_DATE_CONVERTED"] = pd.to_datetime(df_lt2["CHECK_IN_DATE_CONVERTED"], errors="coerce")
                    df_lt2["Μήνας"] = df_lt2["CHECK_IN_DATE_CONVERTED"].dt.strftime("%b")
                    monthly = (df_lt2.groupby("Μήνας")["MONTHLY_AVG_LEAD_TIME"]
                               .mean().reset_index()
                               .rename(columns={"MONTHLY_AVG_LEAD_TIME": "Μέσος Lead Time (ημ.)"}))
                    monthly["Μήνας"] = pd.Categorical(monthly["Μήνας"], categories=MONTH_ORDER, ordered=True)
                    monthly = monthly.sort_values("Μήνας")
                    fig_lt_m = px.bar(
                        monthly, x="Μήνας", y="Μέσος Lead Time (ημ.)",
                        color_discrete_sequence=["#FF5A5F" if studio == "Studio 1" else "#00A699"],
                        title=f"Μηνιαίος Μ.Ο. Lead Time – {studio}",
                    )
                    fig_lt_m.update_layout(height=320, plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
                    st.plotly_chart(fig_lt_m, use_container_width=True)

        # Scatter: lead time vs check-in date
        sc_data = []
        for studio, df_lt in lt_frames.items():
            if "LEAD_TIME_DAYS" in df_lt.columns and "CHECK_IN_DATE_CONVERTED" in df_lt.columns:
                tmp = df_lt[["CHECK_IN_DATE_CONVERTED","LEAD_TIME_DAYS","GUEST_NAME"]].copy()
                tmp["Studio"] = studio
                sc_data.append(tmp)
        if sc_data:
            df_sc = pd.concat(sc_data)
            df_sc["CHECK_IN_DATE_CONVERTED"] = pd.to_datetime(df_sc["CHECK_IN_DATE_CONVERTED"], errors="coerce")
            df_sc = df_sc.dropna(subset=["CHECK_IN_DATE_CONVERTED","LEAD_TIME_DAYS"])
            fig_sc = px.scatter(
                df_sc, x="CHECK_IN_DATE_CONVERTED", y="LEAD_TIME_DAYS",
                color="Studio", hover_data=["GUEST_NAME"],
                color_discrete_map={"Studio 1": "#FF5A5F", "Studio 2": "#00A699"},
                title="Lead Time ανά Κράτηση",
                labels={"CHECK_IN_DATE_CONVERTED": "Check-in Date", "LEAD_TIME_DAYS": "Lead Time (ημέρες)"},
            )
            fig_sc.update_layout(height=380, plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig_sc, use_container_width=True)

# ════════════════════════════════════════════
# TAB 4 – RAW DATA
# ════════════════════════════════════════════
with tab4:
    st.markdown('<h3 class="section-header">Αναλυτικά KPI Δεδομένα</h3>', unsafe_allow_html=True)

    if show1:
        with st.expander("📊 Studio 1 – KPI ανά Μήνα", expanded=True):
            st.dataframe(df1, use_container_width=True, hide_index=True)

    if show2:
        with st.expander("📊 Studio 2 – KPI ανά Μήνα", expanded=True):
            st.dataframe(df2, use_container_width=True, hide_index=True)

    if show1:
        with st.expander("⏱️ Studio 1 – Lead Time Λεπτομέρειες"):
            cols_show = [c for c in ["GUEST_NAME","CHECK_IN_DATE_CONVERTED","BOOKING_DATE",
                                      "LEAD_TIME_DAYS","GLOBAL_AVG_LEAD_TIME","MONTHLY_AVG_LEAD_TIME"]
                         if c in df1_lt.columns]
            st.dataframe(df1_lt[cols_show], use_container_width=True, hide_index=True)

    if show2:
        with st.expander("⏱️ Studio 2 – Lead Time Λεπτομέρειες"):
            cols_show = [c for c in ["GUEST_NAME","CHECK_IN_DATE_CONVERTED","BOOKING_DATE",
                                      "LEAD_TIME_DAYS","GLOBAL_AVG_LEAD_TIME","MONTHLY_AVG_LEAD_TIME"]
                         if c in df2_lt.columns]
            st.dataframe(df2_lt[cols_show], use_container_width=True, hide_index=True)

    # CSV export
    st.markdown("---")
    st.markdown("**📥 Export δεδομένων**")
    exp_frames = []
    if show1: exp_frames.append(df1.assign(Studio="Studio 1"))
    if show2: exp_frames.append(df2.assign(Studio="Studio 2"))
    if exp_frames:
        csv_data = pd.concat(exp_frames).to_csv(index=False).encode("utf-8")
        st.download_button(
            label="⬇️ Κατέβασε KPI CSV",
            data=csv_data,
            file_name="airbnb_kpi_export.csv",
            mime="text/csv",
        )

# ─────────────────────────────────────────────
# FOOTER
# ─────────────────────────────────────────────
st.markdown("---")
st.caption("🏠 Airbnb KPI Dashboard · Data source: Snowflake AIRBNB_DB.RAW · Built with Streamlit + Plotly")

# 1. Βρες την IP του Colab (θα τη χρειαστείς για το password του tunnel)
#!wget -q -O - ipv4.icanhazip.com

# 2. Τρέξε το Streamlit στο background και άνοιξε το tunnel
#!streamlit run airbnb_dashboard.py & npx localtunnel --port 8501