# -*- coding: utf-8 -*-
"""Airbnb_AutoSync_Snowflake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TuY3HB9h4d-QAu5SXC2O_ZyEBR547TAZ
"""

!pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

!pip install -q snowflake-connector-python
print("✅ snowflake-connector-python installed")

import os
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from urllib.parse import urlparse, parse_qs

!pip install -Uq google-auth-oauthlib google-auth-httplib2 google-api-python-client beautifulsoup4 lxml

SCOPES = ["https://www.googleapis.com/auth/gmail.readonly"]
CREDS_FILE = "client_secret_340285840885-1inlvmu1r0hcd4m5rmtth1ctpem7tfm8.apps.googleusercontent.com.json"
TOKEN_FILE = "token.json"

# Detect if running in Colab
try:
    from google.colab import files
    IN_COLAB = True
    print("☁️ Running in Google Colab - Upload credentials required")
except:
    IN_COLAB = False
    print("💻 Running locally - Using local credentials")

creds = None

# 1) Έλεγχος για υπάρχον token.json
if os.path.exists(TOKEN_FILE):
    print("📂 Φόρτωση υπάρχοντος token...")
    try:
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

        # Refresh το token αν έχει λήξει
        if creds.expired and creds.refresh_token:
            print("🔄 Ανανέωση token...")
            creds.refresh(Request())
            with open(TOKEN_FILE, 'w') as f:
                f.write(creds.to_json())
        print("✅ Token φορτώθηκε με επιτυχία")
    except Exception as e:
        print(f"⚠️ Token error: {e}")
        creds = None

# 2) Αν δεν υπάρχει token ή δεν είναι έγκυρο, ξεκινάμε νέα ταυτοποίηση
if not creds or not creds.valid:
    print("🔄 Ξεκίνημα νέας ταυτοποίησης...")

    # Check if client_secret exists
    if not os.path.exists(CREDS_FILE):
        if IN_COLAB:
            print("\n⚠️ Δεν βρέθηκε client_secret.json")
            print("📤 Κάνε upload του αρχείου:")
            print("   client_secret_340285840885-1inlvmu1r0hcd4m5rmtth1ctpem7tfm8.apps.googleusercontent.com.json")
            files.upload()
        else:
            print(f"❌ Error: {CREDS_FILE} δεν υπάρχει στο τρέχον directory")
            print(f"📁 Current directory: {os.getcwd()}")
            print(f"📋 Files in directory: {os.listdir('.')}")
            raise FileNotFoundError(f"Client secret file not found: {CREDS_FILE}")

    flow = InstalledAppFlow.from_client_secrets_file(CREDS_FILE, SCOPES)
    flow.redirect_uri = "http://localhost"

    auth_url, _ = flow.authorization_url(
        prompt="consent",
        access_type="offline",
        include_granted_scopes="true",
        code_challenge_method="S256"
    )

    print("\n🔗 Άνοιξε αυτό το link σε Incognito και συνέχισε ΜΟΝΟ με kostasbotsi@gmail.com:\n")
    print(auth_url)
    print("\nΜετά το Allow, κάνε paste εδώ τον κωδικό ή ΟΛΟ το URL:")
    user_input = input("👉 ").strip()

    if user_input.startswith("http"):
        parsed = urlparse(user_input.replace("&amp;", "&"))
        qs = parse_qs(parsed.query or parsed.fragment)
        code = (qs.get("code") or [None])[0]
    else:
        code = user_input

    assert code, "❌ Δεν βρέθηκε κωδικός. Δοκίμασε ξανά."

    flow.fetch_token(code=code)
    creds = flow.credentials

    with open(TOKEN_FILE, 'w') as f:
        f.write(creds.to_json())
    print("✅ Ταυτοποίηση επιτυχής — token.json αποθηκεύτηκε")

# 3) Δημιουργία Gmail service
service = build("gmail", "v1", credentials=creds)
print("✅ Gmail service δημιουργήθηκε")

# from base64 import urlsafe_b64decode
# from bs4 import BeautifulSoup
# from datetime import datetime, timedelta

# # -------------------------------
# # Συνάρτηση που επιστρέφει RAW body
# # -------------------------------
# def get_airbnb_email_body(service, msg_id):
#     """Επιστρέφει *ολόκληρο* το body του email ως raw text ή html->text."""

#     msg = service.users().messages().get(
#         userId="me",
#         id=msg_id,
#         format="full"
#     ).execute()

#     payload = msg.get("payload", {})

#     # 1) Αν έχει parts → αναζήτησε text/plain
#     if "parts" in payload:
#         for part in payload["parts"]:
#             mime = part.get("mimeType", "")
#             body = part.get("body", {})

#             if mime == "text/plain" and "data" in body:
#                 raw = urlsafe_b64decode(body["data"]).decode("utf-8", errors="ignore")
#                 return raw

#             if mime == "text/html" and "data" in body:
#                 raw_html = urlsafe_b64decode(body["data"]).decode("utf-8", errors="ignore")
#                 return BeautifulSoup(raw_html, "lxml").get_text("\n", strip=True)

#     # 2) Single body
#     body = payload.get("body", {})
#     if "data" in body:
#         raw = urlsafe_b64decode(body["data"]).decode("utf-8", errors="ignore")
#         return raw

#     return "(EMPTY EMAIL BODY)"

# # -------------------------------
# # Φέρε email μόνο των τελευταίων 4 μηνών
# # -------------------------------

# # 4 μήνες = περίπου 120 ημέρες
# four_months_ago = datetime.now() - timedelta(days=120)

# start_date = four_months_ago.strftime("%Y/%m/%d")
# end_date = datetime.now().strftime("%Y/%m/%d")

# query = f'from:airbnb.com after:{start_date} before:{end_date}'

# resp = service.users().messages().list(
#     userId="me",
#     q=query,
#     maxResults=1500     # βάλε όσα θες (10, 20, 200…)
# ).execute()

# msgs = resp.get("messages", [])
# print("📨 Βρέθηκαν:", len(msgs), "Airbnb emails (τελευταίων 4 μηνών).\n")

# # -------------------------------
# # ΤΥΠΩΣΕ ΟΛΟΚΛΗΡΑ ΤΑ EMAILS
# # -------------------------------

# for i, m in enumerate(msgs):
#     msg_id = m["id"]

#     meta = service.users().messages().get(
#         userId="me",
#         id=msg_id,
#         format="metadata",
#         metadataHeaders=["Subject", "Date"]
#     ).execute()

#     subject = next((h["value"] for h in meta["payload"]["headers"] if h["name"]=="Subject"), "(no subject)")
#     date = next((h["value"] for h in meta["payload"]["headers"] if h["name"]=="Date"), "(no date)")

#     print("="*120)
#     print(f"📌 EMAIL #{i}")
#     print("📅 DATE:", date)
#     print("📝 SUBJECT:", subject)
#     print("-"*120)

#     body = get_airbnb_email_body(service, msg_id)
#     print(body)
#     print("\n\n")

# #from base64 import urlsafe_b64decode
# #from bs4 import BeautifulSoup

# # -------------------------------
# # Συνάρτηση που επιστρέφει RAW body
# # -------------------------------
# def get_airbnb_email_body(service, msg_id):
#     msg = service.users().messages().get(
#         userId="me",
#         id=msg_id,
#         format="full"
#     ).execute()

#     payload = msg.get("payload", {})

#     if "parts" in payload:
#         for part in payload["parts"]:
#             mime = part.get("mimeType", "")
#             body = part.get("body", {})

#             if mime == "text/plain" and "data" in body:
#                 raw = urlsafe_b64decode(body["data"]).decode("utf-8", errors="ignore")
#                 return raw

#             if mime == "text/html" and "data" in body:
#                 raw_html = urlsafe_b64decode(body["data"]).decode("utf-8", errors="ignore")
#                 return BeautifulSoup(raw_html, "lxml").get_text("\n", strip=True)

#     body = payload.get("body", {})
#     if "data" in body:
#         raw = urlsafe_b64decode(body["data"]).decode("utf-8", errors="ignore")
#         return raw

#     return "(EMPTY EMAIL BODY)"

# # -------------------------------
# # ✅ Σταθερό εύρος: 1 Ιαν → 31 Μαρ 2026
# # -------------------------------
# start_date = "2026/01/01"
# end_date   = "2026/03/31"

# query = f'from:airbnb.com after:{start_date} before:{end_date}'

# resp = service.users().messages().list(
#     userId="me",
#     q=query,
#     maxResults=2000
# ).execute()

# msgs = resp.get("messages", [])
# print("📨 Βρέθηκαν:", len(msgs), f"Airbnb emails ({start_date} → {end_date}).\n")

# # -------------------------------
# # ΤΥΠΩΣΕ ΟΛΟΚΛΗΡΑ ΤΑ EMAILS
# # -------------------------------
# for i, m in enumerate(msgs):
#     msg_id = m["id"]

#     meta = service.users().messages().get(
#         userId="me",
#         id=msg_id,
#         format="metadata",
#         metadataHeaders=["Subject", "Date"]
#     ).execute()

#     subject = next((h["value"] for h in meta["payload"]["headers"] if h["name"]=="Subject"), "(no subject)")
#     date    = next((h["value"] for h in meta["payload"]["headers"] if h["name"]=="Date"), "(no date)")

#     print("="*120)
#     print(f"📌 EMAIL #{i}")
#     print("📅 DATE:", date)
#     print("📝 SUBJECT:", subject)
#     print("-"*120)

#     body = get_airbnb_email_body(service, msg_id)
#     print(body)
#     print("\n\n")

from base64 import urlsafe_b64decode
from bs4 import BeautifulSoup
from datetime import datetime, timedelta

def get_airbnb_email_body(service, msg_id):
    msg = service.users().messages().get(
        userId="me", id=msg_id, format="full"
    ).execute()
    payload = msg.get("payload", {})
    if "parts" in payload:
        for part in payload["parts"]:
            mime = part.get("mimeType", "")
            body = part.get("body", {})
            if mime == "text/plain" and "data" in body:
                return urlsafe_b64decode(body["data"]).decode("utf-8", errors="ignore")
            if mime == "text/html" and "data" in body:
                raw_html = urlsafe_b64decode(body["data"]).decode("utf-8", errors="ignore")
                return BeautifulSoup(raw_html, "lxml").get_text("\n", strip=True)
    body = payload.get("body", {})
    if "data" in body:
        return urlsafe_b64decode(body["data"]).decode("utf-8", errors="ignore")
    return "(EMPTY EMAIL BODY)"


# ════════════════════════════════════════════════════════════════
# ✅ ΔΥΝΑΜΙΚΟ DATE FILTER — παίρνει από Snowflake την τελευταία
#    κράτηση και ψάχνει emails ΜΕΤΑ από εκείνη την ημερομηνία
# ════════════════════════════════════════════════════════════════
import snowflake.connector
from google.colab import userdata

# SNOWFLAKE_ACCOUNT  = userdata.get('GP30607')
# SNOWFLAKE_USER     = userdata.get('KOSTAS')
# SNOWFLAKE_PASSWORD = userdata.get('Mpotsi!1kostas')
# SNOWFLAKE_DB       = 'AIRBNB_DB'
# SNOWFLAKE_SCHEMA   = 'RAW'
# SNOWFLAKE_WH       = 'AIRBNB_WH'
# SNOWFLAKE_TABLE    = 'RESERVATIONS_RAW'
SNOWFLAKE_ACCOUNT  = 'VFHKJRE-GP30607'
SNOWFLAKE_USER     = 'KOSTAS'
SNOWFLAKE_PASSWORD = 'Mpotsi!1kostas'
SNOWFLAKE_DB       = 'AIRBNB_DB'
SNOWFLAKE_SCHEMA   = 'RAW'
SNOWFLAKE_WH       = 'AIRBNB_WH'
SNOWFLAKE_TABLE    = 'RESERVATIONS_RAW'

print(f"✅ Config ready | Account: {SNOWFLAKE_ACCOUNT} | User: {SNOWFLAKE_USER}")

# Βρες την ημερομηνία του πιο πρόσφατου email στο Snowflake
conn = snowflake.connector.connect(
    account=SNOWFLAKE_ACCOUNT, user=SNOWFLAKE_USER,
    password=SNOWFLAKE_PASSWORD, database=SNOWFLAKE_DB,
    schema=SNOWFLAKE_SCHEMA, warehouse=SNOWFLAKE_WH
)
cur = conn.cursor()
cur.execute(f"SELECT MAX(_LOADED_AT) FROM {SNOWFLAKE_TABLE}")
row = cur.fetchone()
conn.close()

# Αν υπάρχουν δεδομένα → ξεκίνα από εκεί, αλλιώς fallback στο 25/03/2026
FALLBACK_DATE = datetime(2026, 3, 25)

if row and row[0]:
    last_loaded = row[0]  # datetime object
    # 1 μέρα πίσω για overlap ασφαλείας
    fetch_from = last_loaded - timedelta(days=1)
    print(f"📅 Τελευταία εγγραφή στο Snowflake: {last_loaded.strftime('%d/%m/%Y %H:%M')}")
else:
    fetch_from = FALLBACK_DATE
    print(f"⚠️  Δεν βρέθηκαν δεδομένα στο Snowflake. Fallback: {FALLBACK_DATE.strftime('%d/%m/%Y')}")

start_date = fetch_from.strftime("%Y/%m/%d")
end_date   = datetime.now().strftime("%Y/%m/%d")

print(f"🔍 Αναζήτηση emails: {start_date} → {end_date}")

query = f'from:airbnb.com after:{start_date} before:{end_date}'

# ── PAGINATION — φέρνει ΟΛΑ τα emails στο εύρος ──────────────────────────
msgs = []
page_token = None

while True:
    kwargs = {"userId": "me", "q": query, "maxResults": 500}
    if page_token:
        kwargs["pageToken"] = page_token
    resp = service.users().messages().list(**kwargs).execute()
    batch = resp.get("messages", [])
    msgs.extend(batch)
    page_token = resp.get("nextPageToken")
    print(f"   📄 Σελίδα: {len(batch)} emails (σύνολο: {len(msgs)})")
    if not page_token:
        break

print(f"\n📨 Σύνολο: {len(msgs)} Airbnb emails ({start_date} → {end_date}).\n")

# import re
# from datetime import datetime

# MONTH_MAP = {
#     "Ιαν": 1, "Φεβ": 2, "Μαρ": 3, "Απρ": 4,
#     "Μαΐ": 5, "Μαι": 5, "Μα": 5, # Added 'Μα' for May
#     "Ιουν": 6, "Ιουλ": 7,
#     "Αυγ": 8, "Σεπ": 9, "Οκτ": 10, "Νοε": 11, "Δεκ": 12
# }

# def _parse_price(s):
#     """'€ 34,00' ή '-€ 29,03'  →  float"""
#     if not s:
#         return None
#     s = str(s).replace("€", "").replace(" ", "").replace(".", "").replace(",", ".")
#     s = s.replace("—", "-").replace("–", "-").strip()
#     try:
#         return float(s)
#     except:
#         return None

# def _convert_date(date_str, year_hint=None):
#     """'9 Φεβ'  →  datetime(2026, 2, 9)"""
#     if not date_str:
#         return None
#     m = re.search(r'(\d{1,2})\s+([Α-Ωα-ωΆ-Ώ]+)', date_str.strip())
#     if not m:
#         return None
#     day = int(m.group(1))
#     month_str = m.group(2)
#     month = None
#     for k, v in MONTH_MAP.items():
#         if month_str.startswith(k[:3]):
#             month = v
#             break
#     if not month:
#         return None
#     year = year_hint or datetime.now().year
#     try:
#         return datetime(year, month, day)
#     except:
#         return None

# def _convert_time(time_str):
#     """'3:00 μ.μ.'  →  '15:00:00'"""
#     if not time_str:
#         return None
#     t = time_str.strip()
#     pm = bool(re.search(r'μ\.?μ', t, re.IGNORECASE))
#     am = bool(re.search(r'π\.?μ', t, re.IGNORECASE))
#     digits = re.sub(r'[^\d:]', '', t)
#     try:
#         parts = digits.split(":")
#         h = int(parts[0])
#         mn = int(parts[1]) if len(parts) > 1 else 0
#         if pm and h != 12:
#             h += 12
#         if am and h == 12:
#             h = 0
#         return f"{h:02d}:{mn:02d}:00"
#     except:
#         return None

# def _detect_status(subject, body):
#     combined = (subject + " " + body).lower()
#     if any(x in combined for x in ["ακυρώθηκε", "ακύρωση", "cancel"]):
#         return "Canceled"
#     return "Confirmed"

# def parse_airbnb_email(text):
#     """
#     Παίρνει το full body ενός Airbnb email (string) και επιστρέφει dict
#     με ακριβώς τις στήλες του Excel reservations.
#     """
#     rec = {}

#     # ── Email Sent Date ───────────────────────────────────────────────────────
#     m = re.search(r'DATE:\s*(.+?)(?:\n|$)', text)
#     rec["Email Sent Date"] = m.group(1).strip() if m else None

#     # ── Subject ───────────────────────────────────────────────────────────────
#     m = re.search(r'SUBJECT:\s*(.+?)(?:\n|$)', text)
#     rec["Subject"] = m.group(1).strip() if m else None

#     # ── Status / CategoryValue ────────────────────────────────────────────────
#     rec["Status"]        = _detect_status(rec.get("Subject",""), text)
#     rec["CategoryValue"] = 0

#     # ── Guest Name (από subject) ──────────────────────────────────────────────
#     m = re.search(
#         r'[Οο]/[Ηη]\s+(.+?)\s+(?:καταφθάνει|φτάνει|φθάνει)',
#         rec.get("Subject",""), re.IGNORECASE
#     )
#     rec["Guest Name"] = m.group(1).strip() if m else None

#     # ── Listing ───────────────────────────────────────────────────────────────
#     m = re.search(r'(KOSTAS\s+ACROPOLIS\s+STUDIO\s+\d+)', text, re.IGNORECASE)
#     rec["Listing"] = m.group(1).strip().upper() if m else None

#     # ── Check-in / Check-out Date ─────────────────────────────────────────────
#     DAY_PREFIX = r'(?:(?:Δευ|Τρι|Τετ|Πεμ|Παρ|Σαβ|Κυρ)[^\d]*)?'
#     DATE_PAT   = r'(\d{1,2}\s+[Α-Ωα-ω]{2,})'

#     # Pattern 1: Άφιξη … Αναχώρηση … [Δευ] 27 Μαρ … [Παρ] 29 Μαρ  (same block)
#     m = re.search(
#         r'Άφιξη.*?Αναχώρηση.*?' + DAY_PREFIX + DATE_PAT + r'\s+' + DAY_PREFIX + DATE_PAT,
#         text, re.DOTALL
#     )
#     # Pattern 2: Άφιξη\n[Δευ]\n27 Μαρ … Αναχώρηση\n[Παρ]\n29 Μαρ  (dates on own lines)
#     if not m:
#         m = re.search(
#             r'Άφιξη\s*\n' + DAY_PREFIX + r'\s*' + DATE_PAT +
#             r'.*?Αναχώρηση\s*\n' + DAY_PREFIX + r'\s*' + DATE_PAT,
#             text, re.DOTALL
#         )
#     # Pattern 3: Άφιξη: 27 Μαρ  /  Αναχώρηση: 29 Μαρ  (inline colon format)
#     if not m:
#         m = re.search(
#             r'Άφιξη[:\s]+' + DATE_PAT + r'.*?Αναχώρηση[:\s]+' + DATE_PAT,
#             text, re.DOTALL
#         )
#     # Pattern 4: Two dates anywhere after "Ημερομηνίες" or table-like layout
#     if not m:
#         m = re.search(
#             r'(?:Ημερομηνίες|Άφιξη)[^\d]*' + DATE_PAT + r'[^\d]+' + DATE_PAT,
#             text, re.DOTALL
#         )

#     if m:
#         rec["Check-in Date"]  = m.group(1).strip()
#         rec["Check-out Date"] = m.group(2).strip()
#     else:
#         rec["Check-in Date"]  = None
#         rec["Check-out Date"] = None

#     # ── Times ─────────────────────────────────────────────────────────────────
#     times = re.findall(r'(\d{1,2}:\d{2}\s*[μπ]\.\s*[μπ]\.)', text)
#     rec["Check-in Time"]  = times[0].strip() if len(times) > 0 else None
#     rec["Check-out Time"] = times[1].strip() if len(times) > 1 else None

#     # ── Guests Count ──────────────────────────────────────────────────────────
#     m = re.search(r'(\d+)\s+ενήλικ', text)
#     rec["Guests Count"] = int(m.group(1)) if m else None

#     # ── Confirmation Code ─────────────────────────────────────────────────────
#     m = re.search(r'ΚΩΔΙΚ[ΌO][ΣS]\s+ΕΠΙΒΕΒΑ[ΊΙ]ΩΣΗΣ\s*\n\s*([A-Z0-9]{8,12})', text)
#     rec["Confirmation Code"] = m.group(1).strip() if m else None

#     # ── Guest Reviews ─────────────────────────────────────────────────────────
#     m = re.search(r'(\d+)\s+κριτικ', text)
#     rec["Guest Reviews"] = float(m.group(1)) if m else None

#     # ── Nightly Rate × Nights ─────────────────────────────────────────────────
#     m = re.search(r'€\s*([\d\.,]+)\s*x\s*(\d+)\s*διανυκτ', text)
#     if m:
#         rec["Nightly Rate"]  = _parse_price(m.group(1))
#         rec["Nights Count"]  = float(m.group(2))
#         rec["Nightly Total"] = round(rec["Nightly Rate"] * rec["Nights Count"], 2) if rec["Nightly Rate"] else None
#     else:
#         rec["Nightly Rate"]  = None
#         rec["Nights Count"]  = None
#         rec["Nightly Total"] = None

#     # ── Cleaning Fee ──────────────────────────────────────────────────────────
#     m = re.search(r'Κόστος καθαρισμού\s*€\s*([\d\.,]+)', text)
#     rec["Cleaning Fee"] = _parse_price(m.group(1)) if m else None

#     # ── Property Tax ──────────────────────────────────────────────────────────
#     m = re.search(r'Φόροι χρήσης ακινήτου\s*€\s*([\d\.,]+)', text)
#     rec["Property Tax"] = _parse_price(m.group(1)) if m else None

#     # ── Guest Paid Total ──────────────────────────────────────────────────────
#     m = re.search(r'ΣΎΝΟΛΟ\s*\(EUR\)\s*€\s*([\d\.,]+)', text)
#     rec["Guest Paid Total"] = _parse_price(m.group(1)) if m else None

#     # ── Host Payout (ΚΕΡΔΊΖΕΤΕ) ───────────────────────────────────────────────
#     m = re.search(r'ΚΕΡΔΊΖΕΤΕ\s*€\s*([\d\.,]+)', text)
#     rec["Host Payout"] = _parse_price(m.group(1)) if m else None

#     # ── Host Fee (Προμήθεια οικοδεσπότη) ─────────────────────────────────────
#     m = re.search(r'Προμήθεια υπηρεσιών οικοδεσπότη.*?(-?€\s*[\d\.,]+)', text)
#     if m:
#         val = m.group(1).replace("€","").replace(" ","").replace(",",".").replace("—","-").replace("–","-")
#         try:
#             rec["Host Fee"] = abs(float(val))
#         except:
#             rec["Host Fee"] = None
#     else:
#         rec["Host Fee"] = None

#     # ── Canceled fields (για ακυρωμένες κρατήσεις) ───────────────────────────
#     rec["Canceled Reservation Code"] = None
#     rec["Canceled Start Day"]        = None
#     rec["Canceled End Day"]          = None
#     rec["Canceled Month"]            = None
#     rec["Canceled Year"]             = None

#     # ── Date/Time conversions ─────────────────────────────────────────────────
#     year_hint = None
#     if rec.get("Email Sent Date"):
#         ym = re.search(r'\b(\d{4})\b', rec["Email Sent Date"])
#         year_hint = int(ym.group(1)) if ym else None

#     rec["Check-in Date Converted"]  = _convert_date(rec.get("Check-in Date"),  year_hint)
#     rec["Check-out Date Converted"] = _convert_date(rec.get("Check-out Date"), year_hint)
#     rec["Check-in Time Converted"]  = _convert_time(rec.get("Check-in Time"))
#     rec["Check-out Time Converted"] = _convert_time(rec.get("Check-out Time"))

#     return rec


# # ═══════════════════════════════════════════════════════════════════════════════
# #  CELL 5  —  Gmail Loop → DataFrame → Excel
# #  Χρειάζεται: service, msgs, get_airbnb_email_body (από τα προηγούμενα cells)
# # ═══════════════════════════════════════════════════════════════════════════════

# import pandas as pd

# # Λέξεις στο subject που σημαίνουν booking email
# BOOKING_KEYWORDS = [
#     "κράτησ", "Κράτησ", "reservation", "Reservation",
#     "άφιξη", "Άφιξη", "επιβεβαίωση", "Επιβεβαίωση",
#     "υπενθύμιση", "Υπενθύμιση", "φθάνει", "φτάνει", "καταφθάνει"
# ]

# # Σειρά στηλών — ίδια με το Excel σου
# COLUMN_ORDER = [
#     "Email Sent Date", "Status", "CategoryValue", "Subject", "Guest Name", "Listing",
#     "Check-in Date", "Check-out Date", "Check-in Time", "Check-out Time", "Guests Count",
#     "Confirmation Code", "Guest Reviews", "Nightly Rate", "Nights Count", "Nightly Total",
#     "Cleaning Fee", "Property Tax", "Guest Paid Total", "Host Payout", "Host Fee",
#     "Canceled Reservation Code", "Canceled Start Day", "Canceled End Day",
#     "Canceled Month", "Canceled Year",
#     "Check-in Date Converted", "Check-out Date Converted",
#     "Check-in Time Converted", "Check-out Time Converted"
# ]

# all_records = []
# skipped = errors = 0

# print(f"⚙️  Επεξεργασία {len(msgs)} emails...\n{'─'*90}")

# for i, m in enumerate(msgs):
#     msg_id = m["id"]
#     try:
#         # 1) Metadata
#         meta = service.users().messages().get(
#             userId="me", id=msg_id,
#             format="metadata", metadataHeaders=["Subject", "Date"]
#         ).execute()
#         subject = next((h["value"] for h in meta["payload"]["headers"] if h["name"]=="Subject"), "")
#         date    = next((h["value"] for h in meta["payload"]["headers"] if h["name"]=="Date"), "")

#         # 2) Φιλτράρισμα — μόνο booking emails
#         if not any(kw in subject for kw in BOOKING_KEYWORDS):
#             skipped += 1
#             continue

#         # 3) Body
#         body = get_airbnb_email_body(service, msg_id)

#         # 4) Συνδυασμός για τον parser
#         full_text = f"DATE: {date}\nSUBJECT: {subject}\n\n{body}"

#         # 5) Parse
#         record = parse_airbnb_email(full_text)
#         record["_gmail_id"] = msg_id   # εσωτερικό ID (δεν μπαίνει στο Excel)

#         if record.get("Confirmation Code"):
#             all_records.append(record)
#             print(
#                 f"  ✅ #{i:>3}  {record['Confirmation Code']:12}  "
#                 f"{str(record.get('Check-in Date','?')):10} → {str(record.get('Check-out Date','?')):10}  "
#                 f"{str(record.get('Listing','?'))[:25]}"
#             )
#         else:
#             skipped += 1

#     except Exception as e:
#         errors += 1
#         print(f"  ⚠️  #{i} (id={msg_id}): {e}")

# print(f"\n{'─'*90}")
# print(f"✅ Κρατήσεις : {len(all_records)}  |  ⏭️  Παραλείφθηκαν : {skipped}  |  ❌ Σφάλματα : {errors}\n")

# # ── DataFrame ─────────────────────────────────────────────────────────────────
# df_bookings = pd.DataFrame(all_records)

# if not df_bookings.empty:
#     # Αφαίρεση διπλότυπων confirmation code (κρατάμε το πιο πρόσφατο email)
#     df_bookings = (
#         df_bookings
#         .sort_values("Email Sent Date", ascending=False)
#         .drop_duplicates(subset=["Confirmation Code"], keep="first")
#         .reset_index(drop=True)
#     )

#     # Τελική σειρά στηλών (χωρίς το _gmail_id)
#     final_cols = [c for c in COLUMN_ORDER if c in df_bookings.columns]
#     df_bookings = df_bookings[final_cols]

#     # ── Εμφάνιση ──────────────────────────────────────────────────────────────
#     print(f"📋 ΣΥΝΟΠΤΙΚΟΣ ΠΙΝΑΚΑΣ ({len(df_bookings)} κρατήσεις):\n")
#     pd.set_option("display.max_columns", None)
#     pd.set_option("display.width", 250)
#     pd.set_option("display.max_rows", 500)
#     display_cols = [
#         "Email Sent Date","Guest Name","Listing","Check-in Date","Check-out Date",
#         "Confirmation Code","Nights Count","Nightly Rate","Nightly Total",
#         "Cleaning Fee","Property Tax","Guest Paid Total","Host Payout","Host Fee"
#     ]
#     print(df_bookings[[c for c in display_cols if c in df_bookings.columns]].to_string(index=True))

#     # ── Στατιστικά ────────────────────────────────────────────────────────────
#     print(f"\n{'═'*60}")
#     print(f"📈 ΣΤΑΤΙΣΤΙΚΑ:")
#     print(f"   Μοναδικές κρατήσεις  : {len(df_bookings)}")
#     if "Nights Count"   in df_bookings.columns: print(f"   Συνολικές νύχτες     : {df_bookings['Nights Count'].sum():.0f}")
#     if "Host Payout"    in df_bookings.columns: print(f"   Συνολικά έσοδα (€)   : {df_bookings['Host Payout'].sum():.2f}")
#     if "Guest Paid Total" in df_bookings.columns: print(f"   Σύνολο επισκεπτών(€) : {df_bookings['Guest Paid Total'].sum():.2f}")
#     if "Nightly Rate"   in df_bookings.columns: print(f"   Μέση νυχτερινή τιμή  : {df_bookings['Nightly Rate'].mean():.2f} €")
#     print(f"{'═'*60}\n")

#     # ── Αποθήκευση Excel ──────────────────────────────────────────────────────
#     output_file = "airbnb_bookings_all.xlsx"
#     with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
#         df_bookings.to_excel(writer, index=False, sheet_name="Reservations")

#         # Auto-fit column widths
#         ws = writer.sheets["Reservations"]
#         for col in ws.columns:
#             max_len = max(len(str(cell.value)) if cell.value else 0 for cell in col)
#             ws.column_dimensions[col[0].column_letter].width = min(max_len + 2, 40)

#     print(f"💾 Αποθηκεύτηκε: {output_file}")
#     print(f"   ({len(df_bookings)} κρατήσεις × {len(df_bookings.columns)} στήλες)")

# else:
#     print("⚠️  Δεν βρέθηκαν κρατήσεις. Έλεγξε το query ή τα emails.")

#scraped real data
import re
from datetime import datetime
import pandas as pd # Import pandas for pd.isna

MONTH_MAP = {
    "Ιαν": 1, "Φεβ": 2, "Μαρ": 3, "Απρ": 4,
    "Μαΐ": 5, "Μαι": 5, "Μα": 5,
    "Ιουν": 6, "Ιουλ": 7,
    "Αυγ": 8, "Σεπ": 9, "Οκτ": 10, "Νοε": 11, "Δεκ": 12
}

def _parse_price(s):
    """'€ 34,00' ή '-€ 29,03'  →  float"""
    if not s:
        return None
    s = str(s).replace("€", "").replace(" ", "").replace(".", "").replace(",", ".")
    s = s.replace("—", "-").replace("–", "-").strip()
    try:
        return float(s)
    except:
        return None

def _convert_date(date_str, year_hint=None):
    """'9 Φεβ'  →  datetime(2026, 2, 9)"""
    # Handle NaN or None values gracefully
    if pd.isna(date_str):
        return None

    s = str(date_str).strip()
    if not s:
        return None

    m = re.search(r'(\d{1,2})\s+([Α-Ωα-ωΆ-Ώ]+)', s)
    if not m:
        return None
    day = int(m.group(1))
    month_str = m.group(2)
    month = None
    for k, v in MONTH_MAP.items():
        if month_str.startswith(k[:3]):
            month = v
            break
    if not month:
        return None
    year = year_hint or datetime.now().year
    try:
        return datetime(year, month, day)
    except:
        return None

def _convert_time(time_str):
    """'3:00 μ.μ.'  →  '15:00:00'"""
    if not time_str:
        return None
    t = time_str.strip()
    pm = bool(re.search(r'μ\.?μ', t, re.IGNORECASE))
    am = bool(re.search(r'π\.?μ', t, re.IGNORECASE))
    digits = re.sub(r'[^\d:]', '', t)
    try:
        parts = digits.split(":")
        h = int(parts[0])
        mn = int(parts[1]) if len(parts) > 1 else 0
        if pm and h != 12:
            h += 12
        if am and h == 12:
            h = 0
        return f"{h:02d}:{mn:02d}:00"
    except:
        return None

def _detect_status(subject, body):
    combined = (subject + " " + body).lower()
    if any(x in combined for x in ["ακυρώθηκε", "ακύρωση", "cancel"]):
        return "Canceled"
    return "Confirmed"

def parse_airbnb_email(text):
    """
    Παίρνει το full body ενός Airbnb email (string) και επιστρέφει dict
    με ακριβώς τις στήλες του Excel reservations.
    """
    rec = {}

    # ── Email Sent Date ───────────────────────────────────────────────────────
    m = re.search(r'DATE:\s*(.+?)(?:\n|$)', text)
    rec["Email Sent Date"] = m.group(1).strip() if m else None

    # ── Subject ───────────────────────────────────────────────────────────────
    m = re.search(r'SUBJECT:\s*(.+?)(?:\n|$)', text)
    rec["Subject"] = m.group(1).strip() if m else None

    # ── Status / CategoryValue ────────────────────────────────────────────────
    rec["Status"]        = _detect_status(rec.get("Subject", ""), text)
    rec["CategoryValue"] = 0

    # ── Guest Name (από subject) ──────────────────────────────────────────────
    m = re.search(
        r'[Οο]/[Ηη]\s+(.+?)\s+(?:καταφθάνει|φτάνει|φθάνει)',
        rec.get("Subject", ""), re.IGNORECASE
    )
    if not m:
        # Fallback για cancelled: "ο επισκέπτης σας, Ardian"
        m = re.search(r'επισκέπτης σας,\s+([Α-Ωα-ωA-Za-z\s]+?)(?:,\s|\s+έπρεπε)', text)
    rec["Guest Name"] = m.group(1).strip() if m else None

    # ── Listing ───────────────────────────────────────────────────────────────
    m = re.search(r'(KOSTAS\s+ACROPOLIS\s+STUDIO\s+\d+)', text, re.IGNORECASE)
    rec["Listing"] = m.group(1).strip().upper() if m else None

    # ── Check-in / Check-out Date ─────────────────────────────────────────────
    DAY_PREFIX = r'(?:(?:Δευ|Τρι|Τετ|Πεμ|Παρ|Σαβ|Κυρ)[^\d]*)?'
    DATE_PAT   = r'(\d{1,2}\s+[Α-Ωα-ω]{2,})'

    # Pattern 1: Άφιξη … Αναχώρηση … [Δευ] 27 Μαρ … [Παρ] 29 Μαρ  (same block)
    m = re.search(
        r'Άφιξη.*?Αναχώρηση.*?' + DAY_PREFIX + DATE_PAT + r'\s+' + DAY_PREFIX + DATE_PAT,
        text, re.DOTALL
    )
    # Pattern 2: Άφιξη\n[Δευ]\n27 Μαρ … Αναχώρηση\n[Παρ]\n29 Μαρ  (dates on own lines)
    if not m:
        m = re.search(
            r'Άφιξη\s*\n' + DAY_PREFIX + r'\s*' + DATE_PAT +
            r'.*?Αναχώρηση\s*\n' + DAY_PREFIX + r'\s*' + DATE_PAT,
            text, re.DOTALL
        )
    # Pattern 3: Άφιξη: 27 Μαρ  /  Αναχώρηση: 29 Μαρ  (inline colon format)
    if not m:
        m = re.search(
            r'Άφιξη[:\s]+' + DATE_PAT + r'.*?Αναχώρηση[:\s]+' + DATE_PAT,
            text, re.DOTALL
        )
    # Pattern 4: Two dates anywhere after "Ημερομηνίες" or table-like layout
    if not m:
        m = re.search(
            r'(?:Ημερομηνίες|Άφιξη)[^\d]*' + DATE_PAT + r'[^\d]+' + DATE_PAT,
            text, re.DOTALL
        )

    if m:
        rec["Check-in Date"]  = m.group(1).strip()
        rec["Check-out Date"] = m.group(2).strip()
    else:
        # ✅ Pattern 5 (CANCELLED): "11–14 Μαρ" ή "11-14 Μαρ"
        mc = re.search(r'(\d{1,2})\s*[–\-]\s*(\d{1,2})\s+([Α-Ωα-ω]{2,})', text)
        if mc:
            month_part = mc.group(3).strip()
            rec["Check-in Date"]  = f"{mc.group(1)} {month_part}"
            rec["Check-out Date"] = f"{mc.group(2)} {month_part}"
        else:
            rec["Check-in Date"]  = None
            rec["Check-out Date"] = None

    # ── Times ─────────────────────────────────────────────────────────────────
    times = re.findall(r'(\d{1,2}:\d{2}\s*[μπ]\.\s*[μπ]\.)', text)
    rec["Check-in Time"]  = times[0].strip() if len(times) > 0 else None
    rec["Check-out Time"] = times[1].strip() if len(times) > 1 else None

    # ── Guests Count ──────────────────────────────────────────────────────────
    m = re.search(r'(\d+)\s+ενήλικ', text)
    if not m:
        m = re.search(r'(\d+)\s+επισκέπτ', text)
    rec["Guests Count"] = int(m.group(1)) if m else None

    # ── Confirmation Code ─────────────────────────────────────────────────────
    # Pattern 1: Επίσημο section (confirmed emails)
    m = re.search(r'ΚΩΔΙΚ[ΌO][ΣS]\s+ΕΠΙΒΕΒΑ[ΊΙ]ΩΣΗΣ\s*\n\s*([A-Z0-9]{8,12})', text)
    if not m:
        # ✅ Pattern 2: Cancelled — "κράτηση HMKMAEKDHH"
        m = re.search(r'κράτηση\s+([A-Z0-9]{8,12})', text)
    if not m:
        # Pattern 3: Standalone 10-char code
        m = re.search(r'\b(HM[A-Z0-9]{8,10})\b', text)
    rec["Confirmation Code"] = m.group(1).strip() if m else None

    # ── Guest Reviews ─────────────────────────────────────────────────────────
    m = re.search(r'(\d+)\s+κριτικ', text)
    rec["Guest Reviews"] = float(m.group(1)) if m else None

    # ── Nightly Rate × Nights ─────────────────────────────────────────────────
    m = re.search(r'€\s*([\d\.,]+)\s*x\s*(\d+)\s*διανυκτ', text)
    if m:
        rec["Nightly Rate"]  = _parse_price(m.group(1))
        rec["Nights Count"]  = float(m.group(2))
        rec["Nightly Total"] = round(rec["Nightly Rate"] * rec["Nights Count"], 2) if rec["Nightly Rate"] else None
    else:
        rec["Nightly Rate"]  = None
        rec["Nights Count"]  = None
        rec["Nightly Total"] = None

    # ── Cleaning Fee ──────────────────────────────────────────────────────────
    m = re.search(r'Κόστος καθαρισμού\s*€\s*([\d\.,]+)', text)
    rec["Cleaning Fee"] = _parse_price(m.group(1)) if m else None

    # ── Property Tax ──────────────────────────────────────────────────────────
    m = re.search(r'Φόροι χρήσης ακινήτου\s*€\s*([\d\.,]+)', text)
    rec["Property Tax"] = _parse_price(m.group(1)) if m else None

    # ── Guest Paid Total ──────────────────────────────────────────────────────
    m = re.search(r'ΣΎΝΟΛΟ\s*\(EUR\)\s*€\s*([\d\.,]+)', text)
    rec["Guest Paid Total"] = _parse_price(m.group(1)) if m else None

    # ── Host Payout (ΚΕΡΔΊΖΕΤΕ) ───────────────────────────────────────────────
    m = re.search(r'ΚΕΡΔΊΖΕΤΕ\s*€\s*([\d\.,]+)', text)
    rec["Host Payout"] = _parse_price(m.group(1)) if m else None

    # ── Host Fee (Προμήθεια οικοδεσπότη) ─────────────────────────────────────
    m = re.search(r'Προμήθεια υπηρεσιών οικοδεσπότη.*?(-?€\s*[\d\.,]+)', text)
    if m:
        val = m.group(1).replace("€"," ").replace(" ","").replace(",",".").replace("—","-").replace("–","-")
        try:
            rec["Host Fee"] = abs(float(val))
        except:
            rec["Host Fee"] = None
    else:
        rec["Host Fee"] = None

    # ── Date/Time conversions ─────────────────────────────────────────────────
    year_hint = None
    if rec.get("Email Sent Date"):
        ym = re.search(r'\b(\d{4})\b', rec["Email Sent Date"])
        year_hint = int(ym.group(1)) if ym else None

    rec["Check-in Date Converted"]  = _convert_date(rec.get("Check-in Date"),  year_hint)
    rec["Check-out Date Converted"] = _convert_date(rec.get("Check-out Date"), year_hint)
    rec["Check-in Time Converted"]  = _convert_time(rec.get("Check-in Time"))
    rec["Check-out Time Converted"] = _convert_time(rec.get("Check-out Time"))

    # ✅ Canceled fields — γεμίζουν μόνο για ακυρωμένες κρατήσεις
    if rec["Status"] == "Canceled" and rec.get("Confirmation Code"):
        rec["Canceled Reservation Code"] = rec["Confirmation Code"]
        mc = re.search(r'(\d{1,2})\s*[–\-]\s*(\d{1,2})\s+([Α-Ωα-ω]{2,})', text)
        if mc:
            rec["Canceled Start Day"] = int(mc.group(1))
            rec["Canceled End Day"]   = int(mc.group(2))
            rec["Canceled Month"]     = mc.group(3).strip()
            rec["Canceled Year"]      = year_hint
        else:
            rec["Canceled Start Day"] = None
            rec["Canceled End Day"]   = None
            rec["Canceled Month"]     = None
            rec["Canceled Year"]      = year_hint
    else:
        rec["Canceled Reservation Code"] = None
        rec["Canceled Start Day"]        = None
        rec["Canceled End Day"]          = None
        rec["Canceled Month"]            = None
        rec["Canceled Year"]             = None

    return rec


# ═══════════════════════════════════════════════════════════════════════════════
#  CELL 5  —  Gmail Loop → DataFrame → Excel
#  Χρειάζεται: service, msgs, get_airbnb_email_body (από τα προηγούμενα cells)
# ═══════════════════════════════════════════════════════════════════════════════

# import pandas as pd # Already imported at the top of the file if not commented out

# ✅ Λέξεις στο subject — confirmed + cancelled
BOOKING_KEYWORDS = [
    "κράτησ", "Κράτησ", "reservation", "Reservation",
    "άφιξη", "Άφιξη", "επιβεβαίωση", "Επιβεβαίωση",
    "υπενθύμιση", "Υπενθύμιση", "φθάνει", "φτάνει", "καταφθάνει",
    "ακυρώθηκε", "Ακυρώθηκε", "ακύρωση", "Ακύρωση", "cancel"
]

# Σειρά στηλών — ίδια με το Excel σου
COLUMN_ORDER = [
    "Email Sent Date", "Status", "CategoryValue", "Subject", "Guest Name", "Listing",
    "Check-in Date", "Check-out Date", "Check-in Time", "Check-out Time", "Guests Count",
    "Confirmation Code", "Guest Reviews", "Nightly Rate", "Nights Count", "Nightly Total",
    "Cleaning Fee", "Property Tax", "Guest Paid Total", "Host Payout", "Host Fee",
    "Canceled Reservation Code", "Canceled Start Day", "Canceled End Day",
    "Canceled Month", "Canceled Year",
    "Check-in Date Converted", "Check-out Date Converted",
    "Check-in Time Converted", "Check-out Time Converted"
]

all_records = []
skipped = errors = 0

print(f"⚙️  Επεξεργασία {len(msgs)} emails...\n{'─'*90}")

for i, m in enumerate(msgs):
    msg_id = m["id"]
    try:
        # 1) Metadata
        meta = service.users().messages().get(
            userId="me", id=msg_id,
            format="metadata", metadataHeaders=["Subject", "Date"]
        ).execute()
        subject = next((h["value"] for h in meta["payload"]["headers"] if h["name"]=="Subject"), "")
        date    = next((h["value"] for h in meta["payload"]["headers"] if h["name"]=="Date"), "")

        # 2) Φιλτράρισμα — μόνο booking emails (confirmed + cancelled)
        if not any(kw in subject for kw in BOOKING_KEYWORDS):
            skipped += 1
            continue

        # 3) Body
        body = get_airbnb_email_body(service, msg_id)

        # 4) Συνδυασμός για τον parser
        full_text = f"DATE: {date}\nSUBJECT: {subject}\n\n{body}"

        # 5) Parse
        record = parse_airbnb_email(full_text)
        record["_gmail_id"] = msg_id   # εσωτερικό ID (δεν μπαίνει στο Excel)

        if record.get("Confirmation Code"):
            all_records.append(record)
            status_icon = "❌" if record["Status"] == "Canceled" else "✅"
            print(
                f"  {status_icon} #{i:>3}  [{record['Status']:9}]  "
                f"{record['Confirmation Code']:12}  "
                f"{str(record.get('Check-in Date','?')):10} → {str(record.get('Check-out Date','?')):10}  "
                f"{str(record.get('Listing','?'))[:25]}"
            )
        else:
            skipped += 1

    except Exception as e:
        errors += 1
        print(f"  ⚠️  #{i} (id={msg_id}): {e}")

print(f"\n{'─'*90}")
print(f"✅ Κρατήσεις : {len(all_records)}  |  ⏭️  Παραλείφθηκαν : {skipped}  |  ❌ Σφάλματα : {errors}\n")

# ── DataFrame ─────────────────────────────────────────────────────────────────
df_bookings = pd.DataFrame(all_records)

if not df_bookings.empty:
    # Αφαίρεση διπλότυπων confirmation code (κρατάμε το πιο πρόσφατο email)
    df_bookings = (
        df_bookings
        .sort_values("Email Sent Date", ascending=False)
        .drop_duplicates(subset=["Confirmation Code"], keep="first")
        .reset_index(drop=True)
    )

    # Τελική σειρά στηλών (χωρίς το _gmail_id)
    final_cols = [c for c in COLUMN_ORDER if c in df_bookings.columns]
    df_bookings = df_bookings[final_cols]

    # ── Εμφάνιση ──────────────────────────────────────────────────────────────
    print(f"📋 ΣΥΝΟΠΤΙΚΟΣ ΠΙΝΑΚΑΣ ({len(df_bookings)} κρατήσεις):\n")
    pd.set_option("display.max_columns", None)
    pd.set_option("display.width", 250)
    pd.set_option("display.max_rows", 500)
    display_cols = [
        "Email Sent Date","Status","Guest Name","Listing","Check-in Date","Check-out Date",
        "Confirmation Code","Nights Count","Nightly Rate","Nightly Total",
        "Cleaning Fee","Property Tax","Guest Paid Total","Host Payout","Host Fee"
    ]
    print(df_bookings[[c for c in display_cols if c in df_bookings.columns]].to_string(index=True))

    # ── Στατιστικά ────────────────────────────────────────────────────────────
    confirmed = df_bookings[df_bookings["Status"] == "Confirmed"]
    canceled  = df_bookings[df_bookings["Status"] == "Canceled"]

    print(f"\n{'═'*60}")
    print(f"📈 ΣΤΑΤΙΣΤΙΚΑ:")
    print(f"   Μοναδικές κρατήσεις  : {len(df_bookings)}")
    print(f"   ✅ Confirmed          : {len(confirmed)}")
    print(f"   ❌ Canceled           : {len(canceled)}")
    if "Nights Count"     in confirmed.columns: print(f"   Συνολικές νύχτες     : {confirmed['Nights Count'].sum():.0f}")
    if "Host Payout"      in confirmed.columns: print(f"   Συνολικά έσοδα (€)   : {confirmed['Host Payout'].sum():.2f}")
    if "Guest Paid Total" in confirmed.columns: print(f"   Σύνολο επισκεπτών(€) : {confirmed['Guest Paid Total'].sum():.2f}")
    if "Nightly Rate"     in confirmed.columns: print(f"   Μέση νυχτερινή τιμή  : {confirmed['Nightly Rate'].mean():.2f} €")
    print(f"{'═'*60}\n")

    # ── Αποθήκευση Excel ──────────────────────────────────────────────────────
    output_file = "airbnb_bookings_all.xlsx"
    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
        df_bookings.to_excel(writer, index=False, sheet_name="Reservations")

        # Auto-fit column widths
        ws = writer.sheets["Reservations"]
        for col in ws.columns:
            max_len = max(len(str(cell.value)) if cell.value else 0 for cell in col)
            ws.column_dimensions[col[0].column_letter].width = min(max_len + 2, 40)

    print(f"💾 Αποθηκεύτηκε: {output_file}")
    print(f"   ({len(df_bookings)} κρατήσεις × {len(df_bookings.columns)} στήλες)")

else:
    print("⚠️  Δεν βρέθηκαν κρατήσεις. Έλεγξε το query ή τα emails.")

import pandas as pd

output_file = "airbnb_bookings_all.xlsx"
df = pd.read_excel(output_file)
display(df.head())

# Sort the DataFrame by 'Check-in Date Converted' and 'Check-out Date Converted'
df_sorted = df.sort_values(by=['Check-in Date Converted', 'Check-out Date Converted'], ascending=True).reset_index(drop=True)

display(df_sorted.head())

def _convert_date(date_str, year_hint=None):
    """'9 Φεβ'  →  datetime(2026, 2, 9)"""
    # Handle NaN or None values gracefully
    if pd.isna(date_str):
        return None

    s = str(date_str).strip()
    if not s:
        return None

    m = re.search(r'(\d{1,2})\s+([Α-Ωα-ωΆ-Ώ]+)', s)
    if not m:
        return None
    day = int(m.group(1))
    month_str = m.group(2)
    month = None
    for k, v in MONTH_MAP.items():
        if month_str.startswith(k[:3]):
            month = v
            break
    if not month:
        return None
    year = year_hint or datetime.now().year
    try:
        return datetime(year, month, day)
    except:
        return None



df_final_sorted = df_final_sorted.sort_values(
    by=['Check-in Date Datetime'],
    ascending=True
).reset_index(drop=True)

(df_final_sorted)

# First, ensure the 'df' DataFrame still contains the original data after dropping columns
# and that the _convert_date function is accessible (it is in cell 1vtZRZ0xhIqb)

# Define the helper function to extract year from Email Sent Date
def extract_year_from_email_date(email_date_str):
    if email_date_str:
        match = re.search(r'\b(\d{4})\b', email_date_str)
        if match:
            return int(match.group(1))
    return datetime.now().year

# Apply the year extraction
df['email_year_hint'] = df['Email Sent Date'].apply(extract_year_from_email_date)

# Convert 'Check-in Date' and 'Check-out Date' to datetime objects using the year hint
df['Check-in Date Datetime'] = df.apply(lambda row: _convert_date(row['Check-in Date'], row['email_year_hint']), axis=1)
df['Check-out Date Datetime'] = df.apply(lambda row: _convert_date(row['Check-out Date'], row['email_year_hint']), axis=1)

# Define the custom order for the 'Listing' column
listing_order = ['KOSTAS ACROPOLIS STUDIO 1', 'KOSTAS ACROPOLIS STUDIO 2']

# Convert 'Listing' column to a Categorical type with the specified order
df['Listing'] = pd.Categorical(df['Listing'], categories=listing_order, ordered=True)

# Sort the DataFrame first by the custom 'Listing' order,
# then by 'Check-in Date Datetime' and 'Check-out Date Datetime'
df_final_sorted = df.sort_values(
    by=['Listing', 'Check-in Date Datetime', 'Check-out Date Datetime'],
    ascending=[True, True, True]
).reset_index(drop=True)

display(df_final_sorted.head())

columns_to_drop = ['Status', 'CategoryValue', 'Host Fee', 'Canceled Reservation Code','email_year_hint','Canceled Year']
df_final_sorted = df_final_sorted.drop(columns=columns_to_drop, errors='ignore')
display(df_final_sorted.head())

def get_new_status(subject):
    if 'Υπενθύμιση κράτησης' in subject or 'Η κράτηση έχει επιβεβαιωθεί' in subject:
        return 'Confirmed'
    return 'Canceled'

df_final_sorted['New_Status'] = df_final_sorted['Subject'].apply(get_new_status)
display(df_final_sorted.head())

df_final_sorted

df_final_sorted['Real_Host_Payout'] = df_final_sorted['Host Payout'] - df_final_sorted['Property Tax']
(df_final_sorted)

print("Στήλες DataFrame:")
print(list(df_final_sorted.columns))

import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas

df_up = df_final_sorted.copy()

cols_to_drop = [
    'Status', 'CategoryValue', 'Host Fee',
    'Canceled Reservation Code', 'Canceled Year', 'email_year_hint'
]
df_up = df_up.drop(columns=[c for c in cols_to_drop if c in df_up.columns], errors='ignore')

df_up = df_up.sort_values(
    by=['Check-in Date Datetime', 'Check-out Date Datetime'],
    ascending=True
).reset_index(drop=True)

df_up.columns = (
    df_up.columns
    .str.upper()
    .str.replace(' ', '_', regex=False)
    .str.replace('-', '_', regex=False)
)

for col in df_up.select_dtypes(include=['datetime64']).columns:
    df_up[col] = df_up[col].astype(str).replace('NaT', None)

conn = snowflake.connector.connect(
    account=SNOWFLAKE_ACCOUNT, user=SNOWFLAKE_USER,
    password=SNOWFLAKE_PASSWORD, database=SNOWFLAKE_DB,
    schema=SNOWFLAKE_SCHEMA, warehouse=SNOWFLAKE_WH
)
cur = conn.cursor()

try:
    # Temp table
    cur.execute(f'CREATE TEMPORARY TABLE TEMP_RESERVATIONS LIKE {SNOWFLAKE_TABLE}')

    write_pandas(
        conn, df_up, 'TEMP_RESERVATIONS',
        database=SNOWFLAKE_DB, schema=SNOWFLAKE_SCHEMA,
        auto_create_table=False, overwrite=True
    )

    cols     = ', '.join(df_up.columns)
    src_cols = ', '.join([f'src.{c}' for c in df_up.columns])
    cur.execute(f'''
        MERGE INTO {SNOWFLAKE_TABLE} tgt
        USING TEMP_RESERVATIONS src
          ON tgt.CONFIRMATION_CODE = src.CONFIRMATION_CODE
        WHEN MATCHED THEN UPDATE SET
            tgt.NEW_STATUS       = src.NEW_STATUS,
            tgt.REAL_HOST_PAYOUT = src.REAL_HOST_PAYOUT,
            tgt.HOST_PAYOUT      = src.HOST_PAYOUT,
            tgt._LOADED_AT       = CURRENT_TIMESTAMP()
        WHEN NOT MATCHED THEN INSERT ({cols}, _LOADED_AT)
            VALUES ({src_cols}, CURRENT_TIMESTAMP())
    ''')

    r = cur.fetchone()
    print(f'✅ MERGE ολοκληρώθηκε!')
    print(f'   📥 Νέες κρατήσεις : {r[0]}')
    print(f'   🔄 Updated        : {r[1]}')

finally:
    cur.close()
    conn.close()

# Επαλήθευση με σωστή σειρά
conn2 = snowflake.connector.connect(
    account=SNOWFLAKE_ACCOUNT, user=SNOWFLAKE_USER,
    password=SNOWFLAKE_PASSWORD, database=SNOWFLAKE_DB,
    schema=SNOWFLAKE_SCHEMA, warehouse=SNOWFLAKE_WH
)
df_check = pd.read_sql(f'''
    SELECT CONFIRMATION_CODE, GUEST_NAME, LISTING,
           CHECK_IN_DATE_DATETIME, CHECK_OUT_DATE_DATETIME, NEW_STATUS
    FROM {SNOWFLAKE_TABLE}
    ORDER BY CHECK_IN_DATE_DATETIME, CHECK_OUT_DATE_DATETIME
    LIMIT 20
''', conn2)
conn2.close()
print('\n📊 Πρώτες 20 εγγραφές με σωστή σειρά:')
display(df_check)

